# Generated by Django 5.2.9 on 2026-01-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizer_requested',
            field=models.BooleanField(default=False),
        ),
    ]
